### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by maartenbreddels** [oconnor663/blake3-py#10]
Have you considered making a conda-forge package:
https://conda-forge.org/
I'm happy to help set this up. Basically it's following this:
https://conda-forge.org/#add_recipe

**Comment by oconnor663** [comment]
Haven't heard of it before. What does it do?

**Comment by maartenbreddels** [comment]
Conda and mamba are package managers, think of it like apt-get for windows/linux/osx, with real dependency solver, and more than Python, so also compilers/system libraries etc. It also allows the creation of environments, so isolated tree's with their own lib/include/bin dir etc. It's popular for Python, but can be used outside.
For instance, the Python graphviz package has a graphviz dependency, such that you don't have to rely on the system to have it (for windows you can imagine this being an order of magnitude more important).

**Comment by maartenbreddels** [comment]
Regarding maintainance, if you release on pypi, a bot picks it up, and it will be rebuild, if all goes well, you merge the PR, and the release on conda-forge will happen automatically.

PS: conda-forge is a channel on conda, which is maintained by the community, and very large.

**Comment by oconnor663** [comment]
Is there anything in-tree here that we'd need to do to support such a package? I'd be happy to look at a PR if this is something you're interested in working on.

**Comment by maartenbreddels** [comment]
https://pypi.org/project/grayskull/ might be a good start to generate the recipe

**Comment by maartenbreddels** [comment]
no, nothing in-tree, this is an external recipe, that in general will be auto-updated by a bot. Do you want me to generate a recipe and add you as a maintainer?

**Comment by oconnor663** [comment]
Sounds good. I don't know if I'll be able to do any actual work as a maintainer, but I appreciate the nod :-D

**Comment by maartenbreddels** [comment]
It is available on conda forge now:
```
$ conda install -c conda-forge blake3
```

 * https://github.com/conda-forge/blake3-feedstock/
 * https://github.com/conda-forge/staged-recipes/pull/14985
