### ISSUE TITLE
fix CI for 32-bit Windows

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/blake3-py#13]
The upgrade to PyO3 0.12 made [`PYO3_CROSS_INCLUDE_DIR`](https://pyo3.rs/master/building_and_distribution.html) mandatory for that target, but I'm not sure yet how to set it.

**Comment by davidhewitt** [comment]
This was unfortunately a regression for 0.12; see https://github.com/PyO3/pyo3/pull/1179

A fix is merged and is incoming for 0.12.1 which I hope to find time to start publishing later today or tomorrow.

Sorry for the inconvenience.

**Comment by oconnor663** [comment]
Oh fabulous. No, no inconvenience at all. This isn't blocking any features or anything like that. Thanks for the heads up.

**Comment by oconnor663** [comment]
Rerunning CI on `pyo3` 0.12.1, I can confirm that this is fixed. Thanks for the quick turnaround!
