### ISSUE TITLE
binary wheel for apple silicon (M1 cpu)

### ISSUE THREAD

**Issue by ThomasWaldmann** [oconnor663/blake3-py#20]
... would be nice to have.

**Comment by oconnor663** [comment]
Wheels are built on Github Actions with this job: https://github.com/oconnor663/blake3-py/blob/master/.github/workflows/tag.yml

It looks like support for Apple silicon isn't there yet, though obviously there are a lot of people asking for it. This seems to be the thread to follow: https://github.com/actions/virtual-environments/issues/2187

**Comment by messense** [comment]
FYI, you can "cross compile" macOS arm64 and universal2 wheels on x86_64 with maturin, see https://github.com/PyO3/maturin/pull/430/files
