### ISSUE TITLE
please upload python3.10 x86-64 wheels to pypi

### ISSUE THREAD

**Issue by zeevt** [oconnor663/blake3-py#24]

**Comment by oconnor663** [comment]
I just put up https://github.com/oconnor663/blake3-py/pull/25 to enable this. Looks like there's some issue with one of the Windows builds. It might sort itself out once GitHub adds Python 3.10 to their default images?

**Comment by oconnor663** [comment]
I might also wait until Arch Linux rolls out Python 3.10 before I get back to this, unless it's actively blocking anyone? Please let me know.

**Comment by oconnor663** [comment]
Done!
