### ISSUE TITLE
Linux wheel for aarch64 and armv7 architecture ?

### ISSUE THREAD

**Issue by dulfox** [oconnor663/blake3-py#28]
I've seen that you've provided lots of wheel package but could you please provide linux wheel for aarch64 and armv7 architecture ?

**Comment by oconnor663** [comment]
Currently all the wheels are built by GitHub Actions, in this job: https://github.com/oconnor663/blake3-py/blob/master/.github/workflows/push.yml

GitHub doesn't directly support ARM runners as far as I know (but I could be wrong), so getting additional wheels up probably requires some sort of virtualization. I'm sure something with QEMU is possible, but I don't have a ton of experience with this. Things might get a lot easier if we could use https://github.com/rust-embedded/cross directly for this, but I'm not sure.

**Comment by strayer** [comment]
https://github.com/pypa/cibuildwheel uses Docker and qemu to run emulated aarch64 containers to build wheels. I'm currently working on getting this to work with pytaglib and it seems to do its job (although slow, unsurprisingly).

**Comment by robd003** [comment]
I found a build service that's half the price of GitHub actions and has support for arm64 https://buildjet.com/for-github-actions/pricing

**Comment by robd003** [comment]
Great news @oconnor663 GitHub has a beta for arm64 runners!

You can sign-up here: https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

**Comment by ddelange** [comment]
you can simply use the `maturin-action` like pydantic does: https://github.com/pydantic/pydantic-core/blob/e0b4c94054b4bca649d63a8f18843c3baadee1c4/.github/workflows/ci.yml#L395

**Comment by ddelange** [comment]
I saw you use python scripts to upload as release assets.

in constrast, pydantic uses github artifacts for uploading the wheels, and downloads them again in the publish step.

then, you can upload them as release assets and to pypi using dedicated actions ([example](https://github.com/ahupp/python-magic/blob/65fb61c9c9aa6348bb95d1dd71b685720c2a8a23/.github/workflows/wheels.yml#L108-L141)) too. you won't need PyGithub or your python scrips anymore. 100% yml :)

this example ^ uses pypi trusted publishing (no user/pass). all you need to do is add oconnor663/blake3-py as trusted publisher [here](https://pypi.org/manage/project/blake3/settings/publishing/) and add the `permissions` in the github action as per the example.

**Comment by ddelange** [comment]
Opened #45, please review!
