### ISSUE TITLE
Parent module of blake3.blake3.blake3 is builtins

### ISSUE THREAD

**Issue by pawamoy** [oconnor663/blake3-py#38]
I guess it comes from your build system (maturin IIUC?), but `blake3.blake3.blake3` (or the shorter `blake3.blake3`) says its parent module is `builtins`:

```pycon
>>> from blake3 import blake3
>>> blake3.__module__
'builtins'
```

It's problematic because there's no `blake3` object importable from `builtins`.
It makes it impossible to inspect the object without special-casing it. For reference: https://github.com/mkdocstrings/mkdocstrings/issues/451#issuecomment-1353709610

Do you know if there's a way to compile the project so that its objects correctly report their parent modules, for example `blake3.blake3` (and not `builtins`)?

**Comment by oconnor663** [comment]
This is my first time looking at the `__module__` attribute, so I don't have any good ideas off the top of my head. It does look like the pure C implementation has the same property, though, so maybe this is just a native module thing in general? You can test it like this:

```
$ python3 -m venv /tmp/tempenv
$ source /tmp/tempenv/bin/activate
(tempenv) $ cd blake3-py/c_impl
(tempenv) $ pip install .
Processing /home/jacko/blake3-py/c_impl
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for blake3-experimental-c, since package 'wheel' is not installed.
Installing collected packages: blake3-experimental-c
  Running setup.py install for blake3-experimental-c ... done
Successfully installed blake3-experimental-c-0.0.1

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
(tempenv) $ python3
Python 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blake3 import blake3
>>> blake3.__module__
'builtins'
```

**Comment by pawamoy** [comment]
Another project using maturin gives the same result: https://github.com/samuelcolvin/watchfiles.

```console
$ python -m venv .venv
$ . .venv/bin/activate
$ pip install watchfiles
$ python -c 'from watchfiles.main import RustNotify; print(RustNotify.__module__)'
builtins
```

**Comment by HacKanCuBa** [comment]
what about [Pydantic core](https://github.com/pydantic/pydantic-core)?

```
$ python -c 'from pydantic_core import SchemaValidator; print(SchemaValidator.__module__)'
pydantic_core._pydantic_core
```

**Comment by samuelcolvin** [comment]
You just need to set `module` on the `pyclass`, see [here](https://github.com/pydantic/pydantic-core/blob/883048a6be84acd9781b8935d54ede5ff8c03e5e/src/validators/mod.rs#L54).

**Comment by oconnor663** [comment]
Thanks @samuelcolvin!

**Comment by samuelcolvin** [comment]
No problem 👍.

**Comment by oconnor663** [comment]
Released as version 0.3.2.

**Comment by HacKanCuBa** [comment]
Wow, this was fast!! I'm gonna update and test mkdocstrings.
Thanks a lot everyone!

**Comment by pawamoy** [comment]
Yup, thanks for the quick release!!
