### ISSUE TITLE
Precompiled wheel package for CPython3.12

### ISSUE THREAD

**Issue by dnomd343** [oconnor663/blake3-py#41]
From the current latest version `0.3.3`, it only supports python3.11. It was released in December 2022, but now python3.12 has been released, which causes pip installation to be compiled from source code.

As we all know, `blake3` must install the rust runtime in this case, which is quite troublesome for many things, especially in docker build, so it is best to have a pre-built wheel package for CPython3.12.

**Comment by kubedzero** [comment]
@oconnor663  is this something you'd be able to provide in the next couple weeks? https://pypi.org/project/blake3/#files still shows 3.11 and older support, no sign of 3.12 yet. 3.12.1 just dropped a couple days ago.

Thanks!

**Comment by oconnor663** [comment]
I usually put it off until Arch Linux ships the new Python version :) But as long as https://github.com/actions/setup-python supports 3.12 it should just work. I'll give it a shot.

**Comment by oconnor663** [comment]
Released v0.3.4. Python 3.12 binaries should go out with this CI job: https://github.com/oconnor663/blake3-py/actions/runs/7178686753. Fingers crossed!

**Comment by oconnor663** [comment]
Done.
